/android/android2.2//prebuilt/linux-x86/toolchain/arm-eabi-4.4.0/bin//arm-eabi-gcc-4.4.0 -DHAVE_CONFIG_H -DLIBRARY_DIR="\"/lighttpd/lib\"" -DSBIN_DIR="\"/lighttpd/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__ -DOPENSSL_NO_KRB5 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -DHAVE_PCRE_H=1 -DBUILD_ON_ARM -DHAVE_LIBPCRE=1 -DHAVE_LOCALTIME_R=1 -I/android/android2.2/external/openssl/include/ -I/android/android2.2/external/dbus/ -I/android/android2.2/ndk/samples/gxv32xx/pcre/ -I/android/android2.2/external/libxml2/include -I//android/android2.2/external/icu4c/common/ -I /android/android2.2//bionic/libc/arch-arm/include -I /android/android2.2//bionic/libc/include -I /android/android2.2//bionic/libc/kernel/common -I /android/android2.2//bionic/libc/kernel/arch-arm -nostdlib -Bdynamic -Wl,-T,/android/android2.2//build/core/armelf.x -Wl,-dynamic-linker,/system/bin/linker -Wl,--gc-sections -Wl,-z,nocopyreloc  -Wall -W -Wshadow -pedantic -std=gnu99 -MT server.o -MD -MP -MF .deps/server.Tpo -c -o server.o server.c


/android/android2.2//prebuilt/linux-x86/toolchain/arm-eabi-4.4.0/bin//arm-eabi-gcc-4.4.0 -DHAVE_CONFIG_H -DLIBRARY_DIR="\"/lighttpd/lib\"" -DSBIN_DIR="\"/lighttpd/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__ -DOPENSSL_NO_KRB5 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -DHAVE_PCRE_H=1 -DBUILD_ON_ARM -DHAVE_LIBPCRE=1 -DHAVE_LOCALTIME_R=1 -I/android/android2.2/external/openssl/include/ -I/android/android2.2/external/dbus/ -I/android/android2.2/ndk/samples/gxv32xx/pcre/ -I/android/android2.2/external/libxml2/include -I//android/android2.2/external/icu4c/common/ -I /android/android2.2//bionic/libc/arch-arm/include -I /android/android2.2//bionic/libc/include -I /android/android2.2//bionic/libc/kernel/common -I /android/android2.2//bionic/libc/kernel/arch-arm -nostdlib -Bdynamic -Wl,-T,/android/android2.2//build/core/armelf.x -Wl,-dynamic-linker,/system/bin/linker -Wl,--gc-sections -Wl,-z,nocopyreloc  -Wall -W -Wshadow -pedantic -std=gnu99 -MT configfile.o -MD -MP -MF .deps/configfile.Tpo -c -o configfile.o configfile.c



/android/android2.2//prebuilt/linux-x86/toolchain/arm-eabi-4.4.0/bin//arm-eabi-gcc-4.4.0 -DHAVE_PCRE_H=1 -DBUILD_ON_ARM -DHAVE_LIBPCRE=1 -DHAVE_LOCALTIME_R=1 -I/android/android2.2/external/openssl/include/ -I/android/android2.2/external/dbus/ -I/android/android2.2/ndk/samples/gxv32xx/pcre/ -I/android/android2.2/external/libxml2/include -I//android/android2.2/external/icu4c/common/ -I /android/android2.2//bionic/libc/arch-arm/include -I /android/android2.2//bionic/libc/include -I /android/android2.2//bionic/libc/kernel/common -I /android/android2.2//bionic/libc/kernel/arch-arm -nostdlib -Bdynamic -Wl,-T -Wl,/android/android2.2//build/core/armelf.x -Wl,-dynamic-linker -Wl,/system/bin/linker -Wl,--gc-sections -Wl,-z -Wl,nocopyreloc -Wall -W -Wshadow -pedantic -std=gnu99 -Wl,-rpath-link=/android/android2.2//out/target/product/generic/obj/lib -o lighttpd server.o response.o connections.o network.o configfile.o configparser.o request.o proc_open.o buffer.o log.o keyvalue.o chunk.o http_chunk.o stream.o fdevent.o stat_cache.o plugin.o joblist.o etag.o array.o data_string.o data_count.o data_array.o data_integer.o md5.o data_fastcgi.o fdevent_select.o fdevent_linux_rtsig.o fdevent_poll.o fdevent_linux_sysepoll.o fdevent_solaris_devpoll.o fdevent_freebsd_kqueue.o data_config.o bitset.o inet_ntop_cache.o crc32.o connections-glue.o configfile-glue.o http-header-glue.o network_write.o network_linux_sendfile.o network_freebsd_sendfile.o network_writev.o network_solaris_sendfilev.o network_openssl.o splaytree.o status_counter.o -Wl,--export-dynamic  -L/android/android2.2//out/target/product/generic/obj/lib -lc /android/android2.2//prebuilt/linux-x86/toolchain/arm-eabi-4.4.0/lib/gcc/arm-eabi/4.4.0/interwork/libgcc.a -L/android/android2.2/out/target/product/generic/obj/STATIC_LIBRARIES/libxml2_intermediates -lxml2 -L/android/android2.2/out/target/product/generic/system/lib/ -lnvram -ldbus -llog -licuuc -licudata -lstdc++ -lpcre -lm -L/android/android2.2/prebuilt/linux-x86/toolchain/arm-eabi-4.4.0/lib/gcc/arm-eabi/4.4.0/ -lssl -lcrypto /android/android2.2//out/target/product/generic/obj/lib/crtbegin_dynamic.o /android/android2.2//out/target/product/generic/obj/lib/crtend_android.o




