/**
 * 解决antd icon 全量引入导致main文件体积过大的问题
 *
 * https://github.com/ant-design/ant-design/issues/12011#issuecomment-420038579
 *
 * 如果有缺失的Icon 到 https://ant.design/components/icon-cn/ 下查找并添加
 *
 * arrow-down -> ArrowDown
 * 注意有三种风格： Outline, Fill, TwoTone
 */

//  outline
export { default as ArrowDownOutline } from '@ant-design/icons/lib/outline/ArrowDownOutline'
export { default as ArrowLeftOutline } from '@ant-design/icons/lib/outline/ArrowLeftOutline'
export { default as ArrowRightOutline } from '@ant-design/icons/lib/outline/ArrowRightOutline'
export { default as ArrowUpOutline } from '@ant-design/icons/lib/outline/ArrowUpOutline'
export { default as BackwardOutline } from '@ant-design/icons/lib/outline/BackwardOutline'
export { default as BarsOutline } from '@ant-design/icons/lib/outline/BarsOutline'
export { default as BellOutline } from '@ant-design/icons/lib/outline/BellOutline'
export { default as BlockOutline } from '@ant-design/icons/lib/outline/BlockOutline'
export { default as BulbOutline } from '@ant-design/icons/lib/outline/BulbOutline'
export { default as CalendarOutline } from '@ant-design/icons/lib/outline/CalendarOutline'
export { default as CaretDownOutline } from '@ant-design/icons/lib/outline/CaretDownOutline'
export { default as CaretLeftOutline } from '@ant-design/icons/lib/outline/CaretLeftOutline'
export { default as CaretRightOutline } from '@ant-design/icons/lib/outline/CaretRightOutline'
export { default as CaretUpOutline } from '@ant-design/icons/lib/outline/CaretUpOutline'
export { default as CarryOutOutline } from '@ant-design/icons/lib/outline/CarryOutOutline'
export { default as CheckCircleOutline } from '@ant-design/icons/lib/outline/CheckCircleOutline'
export { default as CheckOutline } from '@ant-design/icons/lib/outline/CheckOutline'
export { default as CheckSquareOutline } from '@ant-design/icons/lib/outline/CheckSquareOutline'
export { default as ClockCircleOutline } from '@ant-design/icons/lib/outline/ClockCircleOutline'
export { default as CloseCircleOutline } from '@ant-design/icons/lib/outline/CloseCircleOutline'
export { default as CloseOutline } from '@ant-design/icons/lib/outline/CloseOutline'
export { default as CloseSquareOutline } from '@ant-design/icons/lib/outline/CloseSquareOutline'
export { default as CloudDownloadOutline } from '@ant-design/icons/lib/outline/CloudDownloadOutline'
export { default as CloudUploadOutline } from '@ant-design/icons/lib/outline/CloudUploadOutline'
export { default as CopyOutline } from '@ant-design/icons/lib/outline/CopyOutline'
export { default as DeleteOutline } from '@ant-design/icons/lib/outline/DeleteOutline'
export { default as DoubleLeftOutline } from '@ant-design/icons/lib/outline/DoubleLeftOutline'
export { default as DoubleRightOutline } from '@ant-design/icons/lib/outline/DoubleRightOutline'
export { default as DownCircleOutline } from '@ant-design/icons/lib/outline/DownCircleOutline'
export { default as DownOutline } from '@ant-design/icons/lib/outline/DownOutline'
export { default as DownSquareOutline } from '@ant-design/icons/lib/outline/DownSquareOutline'
export { default as DownloadOutline } from '@ant-design/icons/lib/outline/DownloadOutline'
export { default as DragOutline } from '@ant-design/icons/lib/outline/DragOutline'
export { default as EditOutline } from '@ant-design/icons/lib/outline/EditOutline'
export { default as EllipsisOutline } from '@ant-design/icons/lib/outline/EllipsisOutline'
export { default as EnterOutline } from '@ant-design/icons/lib/outline/EnterOutline'
export { default as ExclamationCircleOutline } from '@ant-design/icons/lib/outline/ExclamationCircleOutline'
export { default as ExclamationOutline } from '@ant-design/icons/lib/outline/ExclamationOutline'
export { default as ExportOutline } from '@ant-design/icons/lib/outline/ExportOutline'
export { default as EyeInvisibleOutline } from '@ant-design/icons/lib/outline/EyeInvisibleOutline'
export { default as EyeOutline } from '@ant-design/icons/lib/outline/EyeOutline'
export { default as FastBackwardOutline } from '@ant-design/icons/lib/outline/FastBackwardOutline'
export { default as FastForwardOutline } from '@ant-design/icons/lib/outline/FastForwardOutline'
export { default as FileAddOutline } from '@ant-design/icons/lib/outline/FileAddOutline'
export { default as FileDoneOutline } from '@ant-design/icons/lib/outline/FileDoneOutline'
export { default as FileOutline } from '@ant-design/icons/lib/outline/FileOutline'
export { default as FormOutline } from '@ant-design/icons/lib/outline/FormOutline'
export { default as ForwardOutline } from '@ant-design/icons/lib/outline/ForwardOutline'
export { default as FullscreenExitOutline } from '@ant-design/icons/lib/outline/FullscreenExitOutline'
export { default as FullscreenOutline } from '@ant-design/icons/lib/outline/FullscreenOutline'
export { default as HistoryOutline } from '@ant-design/icons/lib/outline/HistoryOutline'
export { default as HomeOutline } from '@ant-design/icons/lib/outline/HomeOutline'
export { default as InfoCircleOutline } from '@ant-design/icons/lib/outline/InfoCircleOutline'
export { default as InfoOutline } from '@ant-design/icons/lib/outline/InfoOutline'
export { default as LeftCircleOutline } from '@ant-design/icons/lib/outline/LeftCircleOutline'
export { default as LeftOutline } from '@ant-design/icons/lib/outline/LeftOutline'
export { default as LeftSquareOutline } from '@ant-design/icons/lib/outline/LeftSquareOutline'
export { default as LinkOutline } from '@ant-design/icons/lib/outline/LinkOutline'
export { default as Loading3QuartersOutline } from '@ant-design/icons/lib/outline/Loading3QuartersOutline'
export { default as LoadingOutline } from '@ant-design/icons/lib/outline/LoadingOutline'
export { default as LockOutline } from '@ant-design/icons/lib/outline/LockOutline'
export { default as LoginOutline } from '@ant-design/icons/lib/outline/LoginOutline'
export { default as LogoutOutline } from '@ant-design/icons/lib/outline/LogoutOutline'
export { default as MenuOutline } from '@ant-design/icons/lib/outline/MenuOutline'
export { default as MinusCircleOutline } from '@ant-design/icons/lib/outline/MinusCircleOutline'
export { default as MinusOutline } from '@ant-design/icons/lib/outline/MinusOutline'
export { default as MinusSquareOutline } from '@ant-design/icons/lib/outline/MinusSquareOutline'
export { default as MoreOutline } from '@ant-design/icons/lib/outline/MoreOutline'
export { default as NotificationOutline } from '@ant-design/icons/lib/outline/NotificationOutline'
export { default as NumberOutline } from '@ant-design/icons/lib/outline/NumberOutline'
export { default as PaperClipOutline } from '@ant-design/icons/lib/outline/PaperClipOutline'
export { default as PauseCircleOutline } from '@ant-design/icons/lib/outline/PauseCircleOutline'
export { default as PauseOutline } from '@ant-design/icons/lib/outline/PauseOutline'
export { default as PlusCircleOutline } from '@ant-design/icons/lib/outline/PlusCircleOutline'
export { default as PlusOutline } from '@ant-design/icons/lib/outline/PlusOutline'
export { default as PlusSquareOutline } from '@ant-design/icons/lib/outline/PlusSquareOutline'
export { default as PoweroffOutline } from '@ant-design/icons/lib/outline/PoweroffOutline'
export { default as QuestionCircleOutline } from '@ant-design/icons/lib/outline/QuestionCircleOutline'
export { default as QuestionOutline } from '@ant-design/icons/lib/outline/QuestionOutline'
export { default as ReloadOutline } from '@ant-design/icons/lib/outline/ReloadOutline'
export { default as RightCircleOutline } from '@ant-design/icons/lib/outline/RightCircleOutline'
export { default as RightOutline } from '@ant-design/icons/lib/outline/RightOutline'
export { default as RightSquareOutline } from '@ant-design/icons/lib/outline/RightSquareOutline'
export { default as SearchOutline } from '@ant-design/icons/lib/outline/SearchOutline'
export { default as SelectOutline } from '@ant-design/icons/lib/outline/SelectOutline'
export { default as SettingOutline } from '@ant-design/icons/lib/outline/SettingOutline'
export { default as ShrinkOutline } from '@ant-design/icons/lib/outline/ShrinkOutline'
export { default as SmallDashOutline } from '@ant-design/icons/lib/outline/SmallDashOutline'
export { default as StepBackwardOutline } from '@ant-design/icons/lib/outline/StepBackwardOutline'
export { default as StepForwardOutline } from '@ant-design/icons/lib/outline/StepForwardOutline'
export { default as StopOutline } from '@ant-design/icons/lib/outline/StopOutline'
export { default as ToTopOutline } from '@ant-design/icons/lib/outline/ToTopOutline'
export { default as UnlockOutline } from '@ant-design/icons/lib/outline/UnlockOutline'
export { default as UnorderedListOutline } from '@ant-design/icons/lib/outline/UnorderedListOutline'
export { default as UpCircleOutline } from '@ant-design/icons/lib/outline/UpCircleOutline'
export { default as UpOutline } from '@ant-design/icons/lib/outline/UpOutline'
export { default as UpSquareOutline } from '@ant-design/icons/lib/outline/UpSquareOutline'
export { default as UploadOutline } from '@ant-design/icons/lib/outline/UploadOutline'
export { default as UsbOutline } from '@ant-design/icons/lib/outline/UsbOutline'
export { default as UserAddOutline } from '@ant-design/icons/lib/outline/UserAddOutline'
export { default as UserDeleteOutline } from '@ant-design/icons/lib/outline/UserDeleteOutline'
export { default as UserOutline } from '@ant-design/icons/lib/outline/UserOutline'
export { default as VerticalAlignBottomOutline } from '@ant-design/icons/lib/outline/VerticalAlignBottomOutline'
export { default as VerticalAlignMiddleOutline } from '@ant-design/icons/lib/outline/VerticalAlignMiddleOutline'
export { default as VerticalAlignTopOutline } from '@ant-design/icons/lib/outline/VerticalAlignTopOutline'
export { default as VerticalLeftOutline } from '@ant-design/icons/lib/outline/VerticalLeftOutline'
export { default as VerticalRightOutline } from '@ant-design/icons/lib/outline/VerticalRightOutline'
export { default as WifiOutline } from '@ant-design/icons/lib/outline/WifiOutline'
export { default as ZoomInOutline } from '@ant-design/icons/lib/outline/ZoomInOutline'
export { default as ZoomOutOutline } from '@ant-design/icons/lib/outline/ZoomOutOutline'

// fill
export { default as QuestionCircleFill } from '@ant-design/icons/lib/fill/QuestionCircleFill'
export { default as PlusCircleFill } from '@ant-design/icons/lib/fill/PlusCircleFill'
export { default as InfoCircleFill } from '@ant-design/icons/lib/fill/InfoCircleFill'
export { default as ExclamationCircleFill } from '@ant-design/icons/lib/fill/ExclamationCircleFill'
export { default as CloseCircleFill } from '@ant-design/icons/lib/fill/CloseCircleFill'
export { default as CheckCircleFill } from '@ant-design/icons/lib/fill/CheckCircleFill'
export { default as MinusCircleFill } from '@ant-design/icons/lib/fill/MinusCircleFill'
export { default as PauseCircleFill } from '@ant-design/icons/lib/fill/PauseCircleFill'
